<?php
/**
 * TechDivision_SystemConfigDiff
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * Template for system config scope switcher.
 *
 * @category   TechDivision
 * @package    TechDivision_SystemConfigDiff
 * @subpackage Design
 * @copyright  Copyright (c) 1996-2013 TechDivision GmbH (http://www.techdivision.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version    ${release.version}
 * @since      Class available since Release 0.1.0
 * @author     Florian Sydekum <fs@techdivision.com>
 */
?>
<?php
    $helper = Mage::helper('techdivision_systemconfigdiff');
    $values = $helper->getValues();
?>

<div class="switcher">
    <label for="store_switcher"><?php echo $this->__('Current Configuration Scope:') ?></label>
    <?php echo $this->getHintHtml() ?>
    <select id="store_switcher" class="system-config-store-switcher" onchange="location.href=this.options[this.selectedIndex].getAttribute('url')">
        <?php foreach ($this->getStoreSelectOptions() as $_value => $_option): ?>
        <?php if (isset($_option['is_group'])): ?>
            <?php if ($_option['is_close']): ?>
                </optgroup>
                <?php else: ?>
            <optgroup label="<?php echo $this->escapeHtml($_option['label']) ?>" style="<?php echo $_option['style'] ?>">
        <?php endif; ?>
            <?php continue ?>
            <?php endif; ?>
        <?php if(in_array($this->escapeHtml($_value), $values)): ?>
            <?php $style = $helper->getElementStyle($_option['style']) ?>
            <option class="switcher-diff-error" value="<?php echo $this->escapeHtml($_value) ?>" url="<?php echo $_option['url'] ?>" <?php echo $_option['selected'] ? 'selected="selected"' : '' ?> style="<?php echo $style ?>">
        <?php else: ?>
            <option value="<?php echo $this->escapeHtml($_value) ?>" url="<?php echo $_option['url'] ?>" <?php echo $_option['selected'] ? 'selected="selected"' : '' ?> style="<?php echo $_option['style'] ?>">
        <?php endif; ?>
            <?php echo $this->escapeHtml($_option['label']) ?>
        </option>
        <?php endforeach ?>
    </select>
    <?php if (Mage::getSingleton('admin/session')->isAllowed('system/store')): ?>
    <p style="margin:10px 0 0;">
        <a href="<?php echo $this->getUrl('*/system_store') ?>"><?php echo $this->__('Manage Stores') ?></a>
    </p>
    <?php endif; ?>
</div>