<?php
/**
 * TechDivision_SystemConfigDiff
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * Template for system config tabs.
 *
 * @category   TechDivision
 * @package    TechDivision_SystemConfigDiff
 * @subpackage Design
 * @copyright  Copyright (c) 1996-2013 TechDivision GmbH (http://www.techdivision.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version    ${release.version}
 * @since      Class available since Release 0.1.0
 * @author     Florian Sydekum <fs@techdivision.com>
 */
?>
<?php
    $sectionIds = Mage::helper('techdivision_systemconfigdiff')->getSectionIds();
?>

<?php if($this->getTitle()): ?>
<h3><?php echo $this->getTitle() ?></h3>
<?php endif ?>
<?php if($this->getTabs()): ?>
<ul id="<?php echo $this->getId() ?>" class="tabs config-tabs">
    <?php foreach ($this->getTabs() as $_tab): ?>
    <?php if($_tab->getSections()): ?>
        <li <?php if ($_tab->getClass()): ?>class="<?php echo $_tab->getClass() ?>"<?php endif ?>>
            <dl>
                <dt class="label" style=""><?php echo $_tab->getLabel() ?></dt>
                <?php $_iterator = 1; ?>
                <?php foreach ($_tab->getSections() as $_section): ?>
                    <?php if(in_array($_section->getId(), $sectionIds)): ?>
                        <dd class="config-diff-relative">
                        <div class="tabs-diff-error"></div>
                    <?php else: ?>
                        <dd>
                    <?php endif; ?>
                    <a href="<?php echo $_section->getUrl() ?>" class="<?php echo $_section->getClass() ?><?php if($_section->getId()==$this->getActiveSection()): ?> active<?php endif ?> <?php echo $_section->getIsLast()?'last':'' ?>">
                    <span <?php if($_tab->getId()==$this->getActiveTab()): ?>class="active"<?php endif ?>>
                        <?php echo $_section->getLabel() ?>
                    </span>
                    </a>
                </dd>
                <?php $_iterator++ ; ?>
                <?php endforeach; ?>
            </dl>
        </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>